INSERT INTO public."Contatos"(
    "Id", "Nome", "Telefone", "Email", "Estado", "DDD", "DataCadastro", "DataAtualizacao")
VALUES
    (uuid_generate_v4(), 'Carlos Rodrigues', '9876-5533', 'carlos.rodrigues@example.com', 'MG', '31', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Fernanda Almeida', '9876-5534', 'fernanda.almeida@example.com', 'SP', '11', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Rafaela Costa', '9876-5535', 'rafaela.costa@example.com', 'RJ', '21', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Gustavo Oliveira', '9876-5536', 'gustavo.oliveira@example.com', 'BA', '71', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Larissa Santos', '9876-5537', 'larissa.santos@example.com', 'PE', '81', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Roberto Lima', '9876-5538', 'roberto.lima@example.com', 'PR', '41', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Patrícia Souza', '9876-5539', 'patricia.souza@example.com', 'RS', '51', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Amanda Pereira', '9876-5540', 'amanda.pereira@example.com', 'SC', '47', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Diego Fernandes', '9876-5541', 'diego.fernandes@example.com', 'ES', '27', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Isabela Silva', '9876-5542', 'isabela.silva@example.com', 'GO', '62', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Mariana Santos', '9876-5543', 'mariana.santos@example.com', 'DF', '61', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Lucas Oliveira', '9876-5544', 'lucas.oliveira@example.com', 'AM', '92', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Camila Rodrigues', '9876-5545', 'camila.rodrigues@example.com', 'PA', '91', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Ricardo Almeida', '9876-5546', 'ricardo.almeida@example.com', 'TO', '63', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Juliana Costa', '9876-5547', 'juliana.costa@example.com', 'CE', '85', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Pedro Lima', '9876-5548', 'pedro.lima@example.com', 'MS', '67', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Tatiana Souza', '9876-5549', 'tatiana.souza@example.com', 'AL', '82', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Bruno Oliveira', '9876-5550', 'bruno.oliveira@example.com', 'GO', '62', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Carolina Lima', '9876-5551', 'carolina.lima@example.com', 'BA', '71', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Ricardo Fernandes', '9876-5552', 'ricardo.fernandes@example.com', 'CE', '85', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Tatiana Almeida', '9876-5553', 'tatiana.almeida@example.com', 'MG', '31', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Lucas Costa', '9876-5554', 'lucas.costa@example.com', 'PA', '91', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Fernando Rodrigues', '9876-5556', 'fernando.rodrigues@example.com', 'RS', '51', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Patrícia Lima', '9876-5557', 'patricia.lima@example.com', 'SC', '47', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Rafael Lima', '9876-5561', 'rafael.lima@example.com', 'AL', '82', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Camila Costa', '9876-5560', 'camila.costa@example.com', 'TO', '63', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Roberto Almeida', '9876-5564', 'roberto.almeida@example.com', 'BA', '71', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Amanda Santos', '9876-5565', 'amanda.santos@example.com', 'CE', '85', CURRENT_DATE, NULL),
    (uuid_generate_v4(), 'Luciano Oliveira', '9876-5566', 'luciano.oliveira@example.com', 'MG', '31', CURRENT_DATE, NULL);
